-- SUPERSEDED — do not run this file.
--
-- This originally created a VIEW that exposed every ScholarCompass
-- user's name, league, weekly XP, and badges to ANY visitor, signed in
-- or not, with no per-league restriction. That's no longer the design:
-- users must only ever be able to see players in their OWN current
-- league, enforced by the database itself, not just hidden in the UI.
--
-- See leaderboard_secure.sql instead — it drops this view and replaces
-- it with a proper table + row-level security that only returns rows
-- matching the caller's own league.
