-- ScholarCompass SAT MATH 1v1 Challenge
-- Run in Supabase SQL Editor. Safe to run more than once (idempotent).
-- Re-run it whenever you add SAT Math questions (see satMathQuestions.js header):
-- the answer-key block near the bottom is regenerated by `npm run gen:sat-math-key`.
--
-- DESIGN (why it is built this way)
--  * Players never write to these tables directly. Every action goes through a
--    small SECURITY DEFINER function that checks who you are and what is allowed.
--    That is what stops one player from changing the other player's answers/score.
--  * Scores are computed on the server from stored answers, using a secret answer
--    key table that the browser cannot read.
--  * The match clock lives in the database (started_at). Refreshing the page or
--    reconnecting can never restart or shift the timer.
--  * Separate tables from the IELTS / SAT Reading-Writing 1v1 — those are untouched.

-- ---------------------------------------------------------------- answer key
create table if not exists public.sat_math_answer_key (
  question_id text primary key,
  answer_type text not null default 'mc' check (answer_type in ('mc', 'spr')),
  correct_answer text not null
);
alter table public.sat_math_answer_key enable row level security;   -- no policies = browser cannot read it
revoke all on public.sat_math_answer_key from anon, authenticated;

-- ------------------------------------------------------------------- matches
create table if not exists public.sat_math_matches (
  id uuid default gen_random_uuid() primary key,
  pin text not null,
  host_id uuid not null references auth.users on delete cascade,
  opponent_id uuid references auth.users on delete set null,
  host_name text,
  opponent_name text,
  question_count integer not null check (question_count between 5 and 40),
  time_per_question_seconds integer not null check (time_per_question_seconds between 30 and 300),
  question_ids jsonb not null,
  status text not null default 'waiting'
    check (status in ('waiting', 'ready', 'in_progress', 'completed', 'expired', 'cancelled')),
  started_at timestamptz,
  expires_at timestamptz not null default (now() + interval '20 minutes'),
  host_score integer not null default 0,
  opponent_score integer not null default 0,
  host_last_seen timestamptz,
  opponent_last_seen timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (opponent_id is null or opponent_id <> host_id)
);

drop index if exists sat_math_matches_live_pin_idx;
create unique index sat_math_matches_live_pin_idx
  on public.sat_math_matches (pin)
  where status in ('waiting', 'ready', 'in_progress');

alter table public.sat_math_matches enable row level security;
revoke all on public.sat_math_matches from anon, authenticated;
grant select on public.sat_math_matches to authenticated;   -- read-only, needed for realtime

drop policy if exists "Players can read their own SAT Math match" on public.sat_math_matches;
create policy "Players can read their own SAT Math match"
  on public.sat_math_matches for select
  to authenticated
  using (auth.uid() = host_id or auth.uid() = opponent_id);
-- (deliberately NO insert/update/delete policies: all writes go through the functions below)

-- ------------------------------------------------------------------- answers
create table if not exists public.sat_math_match_answers (
  match_id uuid not null references public.sat_math_matches on delete cascade,
  user_id uuid not null references auth.users on delete cascade,
  question_index integer not null check (question_index >= 0),
  question_id text not null,
  answer text not null,
  is_correct boolean not null,
  answered_at timestamptz not null default now(),
  primary key (match_id, user_id, question_index)   -- this is what blocks duplicate submissions
);
alter table public.sat_math_match_answers enable row level security;   -- no policies: functions only
revoke all on public.sat_math_match_answers from anon, authenticated;

-- ---------------------------------------------------------- internal: settle
-- Applies "time passing" to a match: expires stale lobbies, completes finished
-- matches and computes final scores. Called by the public functions below.
create or replace function public.sat_math_settle(p_id uuid)
returns public.sat_math_matches
language plpgsql
security definer
set search_path = public
as $$
declare
  m public.sat_math_matches;
begin
  select * into m from public.sat_math_matches where id = p_id for update;
  if not found then
    return null;
  end if;

  if m.status in ('waiting', 'ready') and now() > m.expires_at then
    update public.sat_math_matches
       set status = 'expired', updated_at = now()
     where id = p_id
     returning * into m;
  elsif m.status = 'in_progress'
        and now() >= m.started_at + make_interval(secs => m.question_count * m.time_per_question_seconds + 3) then
    update public.sat_math_matches
       set status = 'completed',
           host_score = (select count(*) from public.sat_math_match_answers a
                          where a.match_id = m.id and a.user_id = m.host_id and a.is_correct),
           opponent_score = (select count(*) from public.sat_math_match_answers a
                              where a.match_id = m.id and a.user_id = m.opponent_id and a.is_correct),
           updated_at = now()
     where id = p_id
     returning * into m;
  end if;
  return m;
end;
$$;
revoke all on function public.sat_math_settle(uuid) from public, anon, authenticated;

-- ------------------------------------------------------------ create a match
create or replace function public.create_sat_math_match(p_question_count integer, p_seconds integer, p_name text)
returns public.sat_math_matches
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  total integer;
  ids jsonb;
  new_pin text;
  tries integer := 0;
  m public.sat_math_matches;
begin
  if uid is null then
    raise exception 'Please sign in to create a challenge.';
  end if;
  if p_question_count is null or p_question_count < 5 then
    raise exception 'A challenge needs at least 5 questions.';
  end if;
  if p_seconds is null or p_seconds < 30 then
    raise exception 'Time per question must be at least 30 seconds.';
  end if;
  if p_seconds > 300 then
    raise exception 'Time per question can be at most 300 seconds.';
  end if;

  select count(*) into total from public.sat_math_answer_key;
  if p_question_count > total then
    raise exception 'Only % SAT Math questions are available right now.', total;
  end if;

  -- housekeeping: expire stale lobbies, and drop this player's older unstarted challenges
  update public.sat_math_matches
     set status = 'expired', updated_at = now()
   where status in ('waiting', 'ready') and now() > expires_at;
  update public.sat_math_matches
     set status = 'cancelled', updated_at = now()
   where host_id = uid and status = 'waiting';

  -- the one shared question set, chosen once, stored in order
  select jsonb_agg(question_id order by rn) into ids
    from (
      select question_id, row_number() over (order by random()) as rn
        from public.sat_math_answer_key
    ) t
   where rn <= p_question_count;

  loop
    new_pin := (1000 + floor(random() * 9000))::integer::text;
    begin
      insert into public.sat_math_matches
        (pin, host_id, host_name, question_count, time_per_question_seconds, question_ids, host_last_seen)
      values
        (new_pin, uid, left(coalesce(nullif(trim(p_name), ''), 'Player 1'), 40),
         p_question_count, p_seconds, ids, now())
      returning * into m;
      exit;
    exception when unique_violation then
      tries := tries + 1;
      if tries > 25 then
        raise exception 'Could not reserve a PIN right now. Please try again.';
      end if;
    end;
  end loop;

  return m;
end;
$$;

-- --------------------------------------------------------------- join by PIN
create or replace function public.join_sat_math_match(p_pin text, p_name text)
returns public.sat_math_matches
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  clean_pin text := trim(coalesce(p_pin, ''));
  m public.sat_math_matches;
begin
  if uid is null then
    raise exception 'Please sign in to join a challenge.';
  end if;
  if clean_pin !~ '^[0-9]{4}$' then
    raise exception 'A PIN is exactly 4 digits.';
  end if;

  select * into m from public.sat_math_matches
   where pin = clean_pin and status in ('waiting', 'ready', 'in_progress')
   for update;

  if not found then
    if exists (select 1 from public.sat_math_matches
                where pin = clean_pin and status = 'expired'
                  and created_at > now() - interval '1 day') then
      raise exception 'This challenge has expired. Ask your friend to create a new one.';
    end if;
    raise exception 'No open challenge found for that PIN.';
  end if;

  m := public.sat_math_settle(m.id);
  if m.status = 'expired' then
    raise exception 'This challenge has expired. Ask your friend to create a new one.';
  end if;
  if m.status = 'completed' then
    raise exception 'This challenge has already finished.';
  end if;

  if m.host_id = uid then
    raise exception 'You created this challenge. Share the PIN with your opponent instead.';
  end if;

  if m.opponent_id = uid then
    return m;   -- reconnecting with the same PIN is fine
  end if;

  if m.opponent_id is not null or m.status <> 'waiting' then
    raise exception 'This challenge already has two players.';
  end if;

  update public.sat_math_matches
     set opponent_id = uid,
         opponent_name = left(coalesce(nullif(trim(p_name), ''), 'Player 2'), 40),
         status = 'ready',
         opponent_last_seen = now(),
         expires_at = greatest(expires_at, now() + interval '20 minutes'),
         updated_at = now()
   where id = m.id
   returning * into m;
  return m;
end;
$$;

-- ------------------------------------------------------- host starts the match
create or replace function public.start_sat_math_match(p_match_id uuid)
returns public.sat_math_matches
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  m public.sat_math_matches;
begin
  if uid is null then
    raise exception 'Please sign in.';
  end if;
  m := public.sat_math_settle(p_match_id);
  if m is null or m.host_id <> uid then
    raise exception 'Only the player who created the challenge can start it.';
  end if;
  if m.status = 'in_progress' then
    return m;   -- double click / retry
  end if;
  if m.status = 'expired' then
    raise exception 'This challenge has expired.';
  end if;
  if m.status <> 'ready' or m.opponent_id is null then
    raise exception 'Wait for your opponent to join before starting.';
  end if;

  update public.sat_math_matches
     set status = 'in_progress',
         started_at = now() + interval '4 seconds',   -- short shared "get ready" countdown
         updated_at = now()
   where id = m.id
   returning * into m;
  return m;
end;
$$;

-- ------------------------------------------------------------- leave / cancel
create or replace function public.leave_sat_math_match(p_match_id uuid)
returns public.sat_math_matches
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  m public.sat_math_matches;
begin
  m := public.sat_math_settle(p_match_id);
  if m is null or uid is null or uid not in (m.host_id, coalesce(m.opponent_id, m.host_id)) then
    raise exception 'Challenge not found.';
  end if;

  if m.status in ('waiting', 'ready') and m.host_id = uid then
    update public.sat_math_matches set status = 'cancelled', updated_at = now()
     where id = m.id returning * into m;
  elsif m.status = 'ready' and m.opponent_id = uid then
    update public.sat_math_matches
       set opponent_id = null, opponent_name = null, opponent_last_seen = null,
           status = 'waiting', updated_at = now()
     where id = m.id returning * into m;
  end if;
  return m;
end;
$$;

-- -------------------------------------------------------------- submit answer
create or replace function public.submit_sat_math_answer(p_match_id uuid, p_index integer, p_answer text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  m public.sat_math_matches;
  clean text := trim(coalesce(p_answer, ''));
  win_start timestamptz;
  win_end timestamptz;
  qid text;
  k public.sat_math_answer_key;
  ok boolean;
  inserted integer;
begin
  m := public.sat_math_settle(p_match_id);
  if m is null or uid is null or uid not in (m.host_id, coalesce(m.opponent_id, m.host_id)) then
    raise exception 'Challenge not found.';
  end if;

  if m.status = 'completed' then
    return jsonb_build_object('result', 'late');
  end if;
  if m.status <> 'in_progress' then
    return jsonb_build_object('result', 'not_active');
  end if;
  if p_index is null or p_index < 0 or p_index >= m.question_count
     or clean = '' or length(clean) > 40 then
    return jsonb_build_object('result', 'invalid');
  end if;

  -- each question has its own window on the shared clock (2s grace for network lag)
  win_start := m.started_at + make_interval(secs => p_index * m.time_per_question_seconds);
  win_end := win_start + make_interval(secs => m.time_per_question_seconds);
  if now() < win_start then
    return jsonb_build_object('result', 'early');
  end if;
  if now() > win_end + interval '2 seconds' then
    return jsonb_build_object('result', 'late');
  end if;

  qid := m.question_ids ->> p_index;
  select * into k from public.sat_math_answer_key where question_id = qid;
  if not found then
    return jsonb_build_object('result', 'invalid');
  end if;
  if k.answer_type = 'mc' and clean !~* '^[A-F]$' then
    return jsonb_build_object('result', 'invalid');
  end if;

  ok := lower(clean) = lower(k.correct_answer);

  insert into public.sat_math_match_answers (match_id, user_id, question_index, question_id, answer, is_correct)
  values (m.id, uid, p_index, qid, case when k.answer_type = 'mc' then upper(clean) else clean end, ok)
  on conflict (match_id, user_id, question_index) do nothing;
  get diagnostics inserted = row_count;

  return jsonb_build_object('result', case when inserted = 1 then 'accepted' else 'duplicate' end,
                            'question_index', p_index);
end;
$$;

-- ------------------------------------------- read state (also the heartbeat)
create or replace function public.get_sat_math_match(p_match_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  uid uuid := auth.uid();
  m public.sat_math_matches;
  mine jsonb;
  results jsonb := null;
begin
  m := public.sat_math_settle(p_match_id);
  if m is null or uid is null or uid not in (m.host_id, coalesce(m.opponent_id, m.host_id)) then
    raise exception 'Challenge not found.';
  end if;

  -- heartbeat: lets the other player see whether you are still connected
  if uid = m.host_id and (m.host_last_seen is null or m.host_last_seen < now() - interval '4 seconds') then
    update public.sat_math_matches set host_last_seen = now() where id = m.id returning * into m;
  elsif uid = m.opponent_id and (m.opponent_last_seen is null or m.opponent_last_seen < now() - interval '4 seconds') then
    update public.sat_math_matches set opponent_last_seen = now() where id = m.id returning * into m;
  end if;

  select coalesce(jsonb_agg(jsonb_build_object('question_index', a.question_index, 'answer', a.answer)
                            order by a.question_index), '[]'::jsonb)
    into mine
    from public.sat_math_match_answers a
   where a.match_id = m.id and a.user_id = uid;

  if m.status = 'completed' then
    select coalesce(jsonb_agg(jsonb_build_object(
             'user_id', a.user_id, 'question_index', a.question_index,
             'answer', a.answer, 'is_correct', a.is_correct)
             order by a.user_id, a.question_index), '[]'::jsonb)
      into results
      from public.sat_math_match_answers a
     where a.match_id = m.id;
  end if;

  return jsonb_build_object('match', to_jsonb(m), 'server_now', now(),
                            'my_answers', mine, 'results', results);
end;
$$;

-- --------------------------------------------------------------------- grants
revoke all on function public.create_sat_math_match(integer, integer, text) from public, anon;
revoke all on function public.join_sat_math_match(text, text) from public, anon;
revoke all on function public.start_sat_math_match(uuid) from public, anon;
revoke all on function public.leave_sat_math_match(uuid) from public, anon;
revoke all on function public.submit_sat_math_answer(uuid, integer, text) from public, anon;
revoke all on function public.get_sat_math_match(uuid) from public, anon;
grant execute on function public.create_sat_math_match(integer, integer, text) to authenticated;
grant execute on function public.join_sat_math_match(text, text) to authenticated;
grant execute on function public.start_sat_math_match(uuid) to authenticated;
grant execute on function public.leave_sat_math_match(uuid) to authenticated;
grant execute on function public.submit_sat_math_answer(uuid, integer, text) to authenticated;
grant execute on function public.get_sat_math_match(uuid) to authenticated;

-- ------------------------------------------------------------------ realtime
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and tablename = 'sat_math_matches'
  ) then
    alter publication supabase_realtime add table public.sat_math_matches;
  end if;
end $$;

-- ============================================================ answer key
-- BEGIN GENERATED ANSWER KEY (npm run gen:sat-math-key rewrites this block)
insert into public.sat_math_answer_key (question_id, answer_type, correct_answer) values
  ('A01', 'mc', 'C'),
  ('A02', 'mc', 'C'),
  ('A03', 'mc', 'C'),
  ('A04', 'mc', 'B'),
  ('A05', 'mc', 'A'),
  ('A06', 'mc', 'C'),
  ('A07', 'mc', 'B'),
  ('A08', 'mc', 'C'),
  ('A09', 'mc', 'C'),
  ('A10', 'mc', 'C'),
  ('B01', 'mc', 'B'),
  ('B02', 'mc', 'B'),
  ('B03', 'mc', 'C'),
  ('B04', 'mc', 'D'),
  ('B05', 'mc', 'D'),
  ('B06', 'mc', 'A'),
  ('B07', 'mc', 'C'),
  ('B08', 'mc', 'B'),
  ('B09', 'mc', 'C'),
  ('B10', 'mc', 'C'),
  ('C01', 'mc', 'C'),
  ('C02', 'mc', 'B'),
  ('C03', 'mc', 'D'),
  ('C04', 'mc', 'A'),
  ('C05', 'mc', 'B'),
  ('C06', 'mc', 'C'),
  ('C07', 'mc', 'B'),
  ('C08', 'mc', 'C'),
  ('C09', 'mc', 'C'),
  ('C10', 'mc', 'B'),
  ('D01', 'mc', 'C'),
  ('D02', 'mc', 'C'),
  ('D03', 'mc', 'C'),
  ('D04', 'mc', 'D'),
  ('D05', 'mc', 'B'),
  ('D06', 'mc', 'C'),
  ('D07', 'mc', 'B'),
  ('D08', 'mc', 'C'),
  ('D09', 'mc', 'B'),
  ('D10', 'mc', 'C')
on conflict (question_id) do update
  set answer_type = excluded.answer_type, correct_answer = excluded.correct_answer;
-- END GENERATED ANSWER KEY
